Adjust spaces around comments in settings.yml
conan-io/conan pull request #10230
Opened 2021-12-23 16:36 UTC by johnmcfarlane

Prevents the YAML linter from complaining

Changelog: (Feature | Fix | Bugfix): Describe here your pull request
Docs: https://github.com/conan-io/docs/pull/XXXX

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

The equivalent docs change can be found in [this PR](https://github.com/conan-io/docs/pull/2334).

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2021-12-24 00:53 UTC, memsharded approved these changes
Thanks for contributing this.

There is a test failing (https://ci.conan.io/blue/organizations/jenkins/ConanTestSuite/detail/PR-10230/1/pipeline), because we track changes to settings.yml in order to execute migrations. If you can check the ``migration_settings.py`` and add a new entry with the changes, that would be good enough to pass the test. Otherwise don't worry, we will fix it when possible.

2021-12-24 10:16 UTC, johnmcfarlane commented
Fixed, thanks.

2021-12-27 10:07 UTC, danimtb approved these changes

2021-12-27 10:16 UTC, danimtb requested changes
Sorry, I didn't see this was changing the migrations as well. That is not needed. Just add a new entry for the new settings and the migration step for the next version here: https://github.com/conan-io/conan/blob/develop/conans/client/migrations.py#L104

2022-01-04 09:46 UTC, merged