pylint: add more information about dynamic members
conan-io/conan pull request #10909
Opened 2022-03-28 16:46 UTC by ericLemanissier

Changelog: (Feature | Fix | Bugfix): Describe here your pull request
Docs: https://github.com/conan-io/docs/pull/XXXX

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2022-03-28 17:17 UTC, memsharded requested changes

2022-03-28 17:17 UTC, memsharded commented on conans/pylint_plugin.py
> +    deps_cpp_info_class = MANAGER.ast_from_module_name(
All these members (except ``self.cpp_info``) have already been removed in 2.0. I'd prefer not adding them to the plugin.

On the other hand, ``self.dependencies``, ``self.buildenv_info``, ``self.runenv_info``, ``self.conf``, ``self.conf_info`` could be added.

2022-03-28 17:44 UTC, ericLemanissier commented
Unfortunately, this does not improve the coverage.
`print(self.cpp_infoo)` produces `E1101: Instance of 'TermcapConan' has no 'cpp_infoo' member; maybe 'cpp_info'? (no-member)`, but  `print(self.cpp_info.definitions)` and `print(self.cpp_info.deffffffines)` don't raise any error :/ I don't understand what is wrong.

2022-03-29 12:03 UTC, ericLemanissier commented
even with conan2, CppInfo uses __getattr__, so this change would be useless there too :(

2022-03-29 12:03 UTC, closed without merging