Fix nested Python Popen command
conan-io/conan pull request #11141
Opened 2022-05-01 11:39 UTC by redradist

Please see the stackoverflow issue:
https://stackoverflow.com/questions/72076014/python-popen-git-is-not-recognized-as-an-internal-or-external-command?noredirect=1#comment127352234_72076014

Also please check Popen documentation:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen

Changelog: (Feature | Fix | Bugfix): Describe here your pull request
Docs: https://github.com/conan-io/docs/pull/XXXX

- [X] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

2022-05-01 11:41 UTC, redradist commented
@memsharded Please, check this PR, this issue happens on Windows with nested Popen command.
To fix it I added `shutil.which`

2022-05-01 12:01 UTC, redradist commented
Also I see the following error:
```console
'cmake' is not recognized as an internal or external command,
operable program or batch file.
```
But not found yet place where it happens ...
Also when invoke conan in Popen with create command

2022-05-02 09:54 UTC, memsharded requested changes
In order to evaluate this, it is first necessary to:
- Provide a test, in this same PR, as minimal as possible that would fail without the proposed fix.
- Fix the broken tests, until the build is green

Also, the linked SO question as reference in https://stackoverflow.com/questions/72076014/python-popen-git-is-not-recognized-as-an-internal-or-external-command?noredirect=1#comment127352234_72076014, doesn't seem to be greatly formulated, it is even being downvoted in SO, and it is not being acknowledged as an issue yet there either. So far, I don't think this is a Conan issue that needs to be fixed, there is not enough evidence for that. In order for this to be considered, solid evidence that Python ``Popen(cmd)`` really needs to do a ``which`` to locate ``cmd`` is necessary, but that sounds unlikely.

2022-05-02 19:33 UTC, redradist commented
@memsharded I've found that this issue even reproducible with cmake-conan, try the following config on Windows 10 machine:
```cmake
include(${CMAKE_BINARY_DIR}/conan.cmake)

set(CONAN_COMMAND conan)
conan_cmake_autodetect(settings)
conan_cmake_install(PATH_OR_REFERENCE ${CMAKE_CURRENT_LIST_DIR}
                    BUILD missing
                    REMOTE conancenter
                    SETTINGS ${settings})
```
and the following packages:
```console
[requires]
fmt/8.1.1
flatbuffers/2.0.0

[generators]
cmake
```

2022-05-02 20:36 UTC, memsharded commented
@redradist 

That is not a minimal reproducible example we can add in the test suite. Do not bring ``conan.cmake`` into this, it shouldn't be necessary to reproduce. 

Furthermore, I have tested your above snippets with minimum modifications (like adding missing ``project()`` and ``cmake_minimum_required()`` and, with `` cmake . -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release`` and it is working without issue, no failure there.

2022-05-02 20:45 UTC, redradist commented
> @redradist
> 
> That is not a minimal reproducible example we can add in the test suite. Do not bring `conan.cmake` into this, it shouldn't be necessary to reproduce.
> 
> Furthermore, I have tested your above snippets with minimum modifications (like adding missing `project()` and `cmake_minimum_required()` and, with ` cmake . -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release` and it is working without issue, no failure there.

@memsharded Then it is very strange ...
Probably something on my system ...
This issue reproducible for me only with conan.cmake

2022-11-13 11:58 UTC, redradist commented
Closing this PR.
Issue was related to Windows PATH environment variable longer than 8191 character.
Fixed in `conanex` removing duplicate paths, see https://github.com/redradist/conanex/blob/master/conanex/main.py#L23

2022-11-13 11:58 UTC, closed without merging