raise pyjwt version
conan-io/conan pull request #11350
Opened 2022-05-27 12:06 UTC by memsharded

Changelog: Bugfix: Force ``conan_server`` to use ``pyjwt>=2.4.0`` to solve vulnerability warnings (Conan client was not affected at all, as it doesn't use it, and ``conan_server`` was not affected either, because it was not exposed to that vuln. But solving anyway to avoid security warnings while installing Conan)
Docs: Omit

Close https://github.com/conan-io/conan/issues/11324

2022-05-27 13:14 UTC, lasote approved these changes

2022-05-27 17:10 UTC, memsharded commented
@lasote I have had to do some more changes to pass the tests in py27 and "fake" the ``jwt`` for testing, please re-review

2022-05-30 07:32 UTC, lasote requested changes

2022-05-30 07:32 UTC, lasote commented on conans/server/conanjwt.py
> +except ImportError:  # Just for testing purposes
Time to drop python 2, latest supported 1.48. This is messy.

2022-05-30 09:23 UTC, memsharded commented on conans/server/conanjwt.py
> +except ImportError:  # Just for testing purposes
Agree, done

2022-05-30 15:13 UTC, lasote approved these changes
Change the changelog, probably worth it to mention this is only python 3.
About that, Should we introduce this in the `setup.py`? we don't have it in the develop2 either, but probably we should?

(https://packaging.python.org/en/latest/guides/dropping-older-python-versions/#specify-the-version-ranges-for-supported-python-distributions)

2022-05-30 15:35 UTC, merged