Python 3 with nice failure for python2
conan-io/conan pull request #11360
Opened 2022-05-30 15:43 UTC by lasote

Changelog: omit
Docs: omit

2022-05-30 15:52 UTC, memsharded requested changes

2022-05-30 15:52 UTC, memsharded commented on setup.py
> +    python_requires='>=3.7',
```suggestion
    python_requires='>=3.6',
```

2022-05-30 16:14 UTC, memsharded approved these changes

2022-05-30 17:43 UTC, merged

2022-06-01 04:12 UTC, paulocoutinhox commented
This is wrong, no? Because `python>=3.6` include version 3.6.
@memsharded @lasote

2022-06-01 05:34 UTC, lasote commented
Sorry the title was wrong. The minimum supported is 3.6