Add new ``--build=missing(pattern)`` and apply it to ``conan create``
conan-io/conan pull request #11382
Opened 2022-06-02 12:49 UTC by memsharded

Proof of concept for https://github.com/conan-io/conan/issues/11293

2022-06-06 13:56 UTC, memsharded commented
Update after review:

- The default keeps the old one ``conan create`` always build from source, unless different ``--build`` specified
- Changed syntax to ``--build missing:pattern`` (Note, @lasote for some reason it doesn't need ``--build=missing:pkg*``, but a ``--build=missing:pkg`` also seems to work
- Added new test to cover the behavior.

2022-06-06 14:00 UTC, lasote approved these changes

2022-06-06 14:01 UTC, lasote commented
> Changed syntax to --build missing:pattern (Note, @lasote for some reason it doesn't need --build=missing:pkg*, but a --build=missing:pkg also seems to work

🤔 will check

2022-06-06 14:32 UTC, lasote requested changes
I don't know what is going on but something is not working at all.
This code is never called for the "pkg" reference:

```
    def should_build_missing(self, conanfile):
        for pattern in self.build_missing_patterns:
            if ref_matches(conanfile.ref, pattern, is_consumer=False):
                return True
```
So it really doesn' t matter whether you use the "pkg*" or "pkg".

2022-06-07 07:58 UTC, memsharded commented
Test updated in https://github.com/conan-io/conan/pull/11382/commits/052e10c1742264cebd9fd59169f32200b9b0e432, please @lasote re-check, I hope now it is more clear the behavior.

2022-06-07 08:35 UTC, franramirez688 approved these changes

2022-06-08 13:15 UTC, lasote approved these changes
👍🏼

2022-06-08 13:19 UTC, czoido approved these changes

2022-06-08 13:20 UTC, merged