Feature/develop2 robust rmdir move
conan-io/conan pull request #11537
Opened 2022-06-27 22:32 UTC by memsharded

Close https://github.com/conan-io/conan/issues/11528

2022-06-27 22:34 UTC, memsharded commented on conans/util/files.py
> +    for i in range(retries):
Can be done only for Windows if we think it is worth simpler in other OSs

2022-07-04 10:01 UTC, lasote commented on conans/util/files.py
> +    for i in range(retries):
Yes, I would say that problem is Windows copyrighted.

2022-07-04 10:01 UTC, lasote requested changes

2022-07-04 10:01 UTC, lasote commented on conans/util/files.py
> +def renamedir(old_path, new_path):
idem

2022-07-05 08:17 UTC, memsharded commented
Done, made the functions with retries only-windows, please check

2022-07-07 06:47 UTC, lasote approved these changes

2022-07-07 06:47 UTC, merged