Add new layout() test for projects sharing common code in parent folders
conan-io/conan pull request #11556
Opened 2022-06-30 12:53 UTC by memsharded

Changelog: omit
Docs: omit

2022-06-30 15:36 UTC, prince-chrismc approved these changes
This works 🚀 

The downside to the custom layout is losing the generator folder being set by `cmake_layout` and it's [handling around the conf and multi](https://github.com/conan-io/conan/commit/005fc53485557b0a570bb71670f2ca9c66082165#diff-dbf5d536275be2e3c8db49e46f4b65b830abcb38becc44a077c7d3271c2e0d82R28-R31)

2022-07-08 15:52 UTC, prince-chrismc commented on conan/tools/cmake/layout.py
> +    conanfile.folders.source = src_folder if not subfolder else os.path.join(subfolder, src_folder)
sub folder is above source dir? 😕 

Is that from the perspective of the root folder?

2022-07-08 15:57 UTC, memsharded commented on conan/tools/cmake/layout.py
> +    conanfile.folders.source = src_folder if not subfolder else os.path.join(subfolder, src_folder)
Yes, the idea is that ``subfolder`` is from the "root" folder, to get you back to the subproject folder where the conanfile.py is. And then, the ``src_folder`` defines the source folder within that subproject (typically, where the CMakeLists.txt of that subproject is)

2022-07-08 16:01 UTC, prince-chrismc approved these changes

2022-07-11 06:55 UTC, lasote requested changes
I think understanding why going to `..` to later come back to `pkg` is too much. There is no way a "subfolder" argument will be interpreted and used in the correct way.

2022-07-11 10:39 UTC, memsharded commented on conans/test/functional/layout/test_in_subfolder.py
> +                cmake_layout(self, subfolder="pkg")
```suggestion
            def layout(self):
                self.folders.root = ".."
                self.folders.subproject = "pkg"
                cmake_layout(self)
```

2022-07-11 15:42 UTC, memsharded commented on conans/test/functional/layout/test_in_subfolder.py
> +                cmake_layout(self, subfolder="pkg")
Done

2022-07-11 17:04 UTC, memsharded commented
I have changed the approach, with a ``self.folders.subproject`` definition, and extended its application to other generators as well. Please re-check.

2022-07-12 06:22 UTC, lasote approved these changes

2022-07-12 06:22 UTC, lasote commented on conans/model/layout.py
> +        # The relative location wrt to the project root of the subproject containing the
```suggestion
        # The relative location with respect to the project root of the subproject containing the
```

We hate acronyms

2022-07-12 08:23 UTC, franramirez688 approved these changes

2022-07-12 15:08 UTC, prince-chrismc approved these changes
👍 subproject is a more clear name

2022-07-12 15:15 UTC, merged