Add conan.conanrc file to setup the conan user home
conan-io/conan pull request #11675
Opened 2022-07-20 07:03 UTC by czoido

You can create a _conan.conanrc_ file in the folder where you are running conan, it can have this content:

Set the conan home to an absolute folder
```
[init]
conan_home=/absolute/folder
```

Set the conan home to a relative folder inside the current folder
```
[init]
conan_home=./relative folder/inside current folder
```

Set the conan home to a relative folder outside the current folder
```
[init]
conan_home=../relative folder/outside current folder
```

Set the conan home to a path containing the `~` that will be expanded to the system's user home
```
[init]
conan_home=~/use the user home to expand it
```

2022-07-20 07:24 UTC, lasote commented on conans/paths/__init__.py
> +    conanrc_config = ConfigParser()
Why not a "key=value" file without sections? Do we expect to have multiple?

2022-07-20 07:37 UTC, czoido commented on conans/paths/__init__.py
> +    conanrc_config = ConfigParser()
Probably not, I can simplify it 👍

2022-07-20 08:40 UTC, czoido commented on conans/paths/__init__.py
> +            if conan_home and (conan_home[:2] in ("./", ".\\") or conan_home.startswith("..")):
```suggestion
            if conan_home[:2] in ("./", ".\\") or conan_home.startswith(".."):
```

2022-07-20 08:56 UTC, memsharded commented on conans/paths/__init__.py
> +            conanrc_path = os.path.join(os.getcwd(), "conan.conanrc")
I think the file can be called just ``.conanrc``
```suggestion
            conanrc_path = os.path.join(os.getcwd(), ".conanrc")
```

2022-07-20 08:56 UTC, memsharded commented on conans/paths/__init__.py
> +                conan_home = os.path.abspath(os.path.join(os.getcwd(), conan_home))
The home should be computed relative to the folder containing the ``.conanrc``, not ``os.getcwd()``, otherwise it will be confusing.

2022-07-20 08:56 UTC, memsharded commented on conans/test/unittests/paths/user_home_test.py
> +        with open(os.path.join(_temp_folder, "conan.conanrc"), 'w+') as file:
```suggestion
        with open(os.path.join(_temp_folder, ".conanrc"), 'w+') as file:
```

2022-07-20 09:19 UTC, czoido commented on conans/paths/__init__.py
> +                conan_home = os.path.abspath(os.path.join(os.getcwd(), conan_home))
I search for the `.conanrc` file in the `os.getcwd()` so it will be the same folder...
I assumed this file is in the root folder of a repo and that you call conan from that folder. Should we traverse the directory structure to find for this files in some way?

2022-07-20 09:36 UTC, memsharded commented on conans/paths/__init__.py
> +                conan_home = os.path.abspath(os.path.join(os.getcwd(), conan_home))
Yes, that was the original idea. Too often you are not in the root, but in a ``build`` subfolder or something.

2022-07-20 11:28 UTC, memsharded approved these changes

2022-07-21 07:06 UTC, lasote requested changes
The issue to be closed described also that we wanted to recover the "storage" path (different from the cache). Right?

2022-07-21 07:06 UTC, lasote commented on conans/paths/__init__.py
>                        (line.split('=') for line in open(conanrc_path).read().splitlines() if
I was wondering if this file descriptor keeps open until the process finish but apparently is doing well, it gets closed after the `for` loop. Just for my own knowledge, is that a feature of python3? it was always like that? I cannot find documentation about the automatic close. If it was accidental, should we read the contents first?

2022-07-21 07:13 UTC, czoido commented on conans/paths/__init__.py
>                        (line.split('=') for line in open(conanrc_path).read().splitlines() if
I found some info on Stack Overflow and apparently the garbage collection will handle this in different ways depending on the Python implementation, but I think that if we want to make sure that this won't be problematic in the future we should probably change it. I think I'll better remove the comprehension.

2022-07-21 07:55 UTC, memsharded commented
@lasote the storage  path was already merged in https://github.com/conan-io/conan/pull/11672

2022-07-21 08:01 UTC, lasote approved these changes

2022-07-21 08:16 UTC, merged

2022-08-02 21:48 UTC, prince-chrismc commented
This made playing with Conan 2.0 so much easier! ❤️ 

Now I just keep `.conanrc` in my root project folder with `conan_home=~/.conan2` and magic 🧙 I get

```sh
$ conan config home
Current Conan home: /Users/christopherm/.conan2
```

👏

2022-08-15 22:06 UTC, memsharded commented
@prince-chrismc To make things clear, ``.conan2`` is already the default name in Conan 2.0 beta to avoid colliding with Conan 1.X. But the feature should work for other names too, please check

2022-08-16 02:22 UTC, prince-chrismc commented
It does, `conan_home=/tmp/meetup/.conan_two`

```
Current Conan home: /Users/christopherm/.conan_two
 christopherm@christopherm-mac  ~/meetup   conan2 ±  conan config home
Initialized file: '/tmp/meetup/.conan_two/settings.yml'
Initialized file: '/tmp/meetup/.conan_two/extensions/plugins/compatibility/compatibility.py'
Initialized file: '/tmp/meetup/.conan_two/extensions/plugins/compatibility/app_compat.py'
Initialized file: '/tmp/meetup/.conan_two/extensions/plugins/compatibility/cppstd_compat.py'
Initialized file: '/tmp/meetup/.conan_two/extensions/plugins/profile.py'
Current Conan home: /tmp/meetup/.conan_two
```

2022-08-20 03:44 UTC, blackliner commented
Amazing, thanks for this!