Added endeavouros to the distro list in `with_pacman` in oss.py  #11970
conan-io/conan pull request #11971
Opened 2022-08-27 12:01 UTC by cchulo

Changelog: (Bugfix): Adds "endeavouros" to the list of distros in with_pacman #11970

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2022-08-27 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=11971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=11971) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=11971) it.</sub>

2022-08-27 12:05 UTC, memsharded requested changes
Thanks for contributing

The integration that you are modifying is legacy, and shouldn't be used anymore. 
The recommended one is in ``from conan.tools.system ...``

Please have a look to https://docs.conan.io/en/latest/reference/conanfile/tools.html, and the place to do the modifications is in https://github.com/conan-io/conan/blob/develop/conan/tools/system/package_manager.py

2022-08-27 12:12 UTC, cchulo commented
@memsharded done

2022-08-28 21:10 UTC, memsharded approved these changes

2022-08-28 21:17 UTC, memsharded requested changes
Have you tried this manually and it is working?
I thought it was ok, but I did a routine check on https://github.com/python-distro/distro/blob/master/src/distro/distro.py, and I don't think that ``distro.id()`` will be returning the ``endeavouros`` string. Am I missing something? Is ``distro`` capable of returning this even if not documented explicitly in the project?

2022-08-28 21:49 UTC, cchulo commented
well this is why I had the previous change, I traced the code back to oss.py, though you said it was legacy, that's what led me to that file

2022-08-28 22:03 UTC, cchulo commented
Actually I should be more specific, the initial commit to oss.py was traced back from OpenGL's recipe, tools which is imported from `conans` and then just reading that code led me to `oss.py`, I decided not to change that file at your advise that it is legacy and instead implemented the change at the other location you suggested, not exactly sure how to test it to ensure that it is working. Still with your earlier advise to setup `[conf]` flags in my profile I was able to work around this anyway

2022-08-28 22:17 UTC, memsharded commented
No, the code is ok, the change you did put the fix in the right place. I think the problem would be the same in the other legacy place as well.

The underlying issue is that Conan uses the return of ``distro.id()`` to feed it into those dictionaries. But it seems that ``distro.id()`` doesn't return ``endeavouros`` string, at least my inspection of the ``distro`` code. The way to check it would be just ``import distro + distro.id()`` in your ``python`` in your system.

2022-08-29 08:47 UTC, cchulo commented
> No, the code is ok, the change you did put the fix in the right place. I think the problem would be the same in the other legacy place as well.
> 
> The underlying issue is that Conan uses the return of `distro.id()` to feed it into those dictionaries. But it seems that `distro.id()` doesn't return `endeavouros` string, at least my inspection of the `distro` code. The way to check it would be just `import distro + distro.id()` in your `python` in your system.

I had my hard drive fail, its going to take me a bit to get back to you, I will ping you as soon as I am able to, would be back up and running, but I have work, I may not be able to get back to this until this upcoming weekend

2022-09-04 22:49 UTC, cchulo commented
@memsharded sorry for that week-long delay, got around to it, and yes, distro.id() on my OS returns correctly:

```shell
>>> import distro
>>> distro.id()
'endeavouros'
>>> 
```

2022-09-05 14:07 UTC, memsharded approved these changes

2022-09-05 14:07 UTC, merged