Added GCC 13 support
conan-io/conan pull request #13007
Opened 2023-01-30 16:12 UTC by xvitaly

Added GCC 13 support.

2023-01-30 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=13007) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=13007) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=13007) it.</sub>

2023-02-02 05:26 UTC, SSE4 approved these changes

2023-05-05 08:20 UTC, H-G-Hristov commented
@memsharded Will this be included in the 1.x.x? GCC 13.1 has been released: https://gcc.gnu.org

I need GCC 13/14... support in the 1.x.x for some time as I won't be able to move to conan 2 any time soon.

2023-05-05 08:21 UTC, H-G-Hristov requested changes

2023-05-05 08:21 UTC, H-G-Hristov commented on conans/client/conf/__init__.py
> +                      "13"]
```suggestion
                      "13", "13.1"]
```

2023-05-08 16:05 UTC, closed without merging

2023-05-08 20:43 UTC, memsharded commented
Yes, lets add this to default settings, sorry for the wait, it is being super busy here with 2.0

2023-05-08 20:48 UTC, memsharded commented
https://github.com/conan-io/conan/pull/13848 for next 1.60 (and also 2.0.5)