Nicer error in the compatibility plugin with custom compilers
conan-io/conan pull request #13328
Opened 2023-03-05 00:03 UTC by RubenRBS

Changelog: Bugfix: Nicer error in the compatibility plugin with custom compilers
Docs: Omit

After seeing https://github.com/conan-io/conan/issues/13325, figured I'd improve the UX of the raised error. My first idea was to make the function return an empty list if the compiler was not known, but that would change current behaviour and so I decided to at least improve the generated exception, happy to discuss if going that way would work or not (Mostly so I get to learn about it a bit more :))

Also, I noticed that the plugin code itself is _not_ currently directly tested and we might want to look into improving that, but I tried and got hit a wall because of how the function is defined in the code, it makes it hard to test. We could get it to run by running the same code that the `test_migrations` code does, but I was not able to come up with a test that exercised the compatibility feature, so any help is welcomed!

2023-03-05 10:55 UTC, memsharded commented
> After seeing https://github.com/conan-io/conan/issues/13325, figured I'd improve the UX of the raised error. My first idea was to make the function return an empty list if the compiler was not known, but that would change current behaviour and so I decided to at least improve the generated exception, happy to discuss if going that way would work or not (Mostly so I get to learn about it a bit more :))

Yes, definitely a better error until we discuss what would be a better default (taking into account that there will be users adding their own compilers to ``settings.yml``, that would hit this error).

> Also, I noticed that the plugin code itself is not currently directly tested and we might want to look into improving that, but I tried and got hit a wall because of how the function is defined in the code, it makes it hard to test. We could get it to run by running the same code that the test_migrations code does, but I was not able to come up with a test that exercised the compatibility feature, so any help is welcomed!

I think there are tests like ``TestCacheCompatibles`` that validate behavior of ``compatibility.py``, isn't that enough?

2023-03-06 17:29 UTC, memsharded requested changes

2023-03-06 17:29 UTC, memsharded commented on conans/client/graph/compatibility.py
> +    if cppstd_possible_values is None:
Lets change it to return [] and warning

2023-03-06 18:34 UTC, memsharded approved these changes
I think a unit test would be great.

2023-03-08 11:20 UTC, RubenRBS commented
Done, I have added a case where it all works just to make sure

2023-03-08 17:38 UTC, merged