allow to copy & paste from compact format into conan-lock-add
conan-io/conan pull request #15262
Opened 2023-12-13 00:10 UTC by memsharded

Changelog: Feature: Allow copy&paste of recipe revisions with timestamps from ``--format=compact`` into ``conan lock add``
Docs: TODO

2023-12-13 00:42 UTC, RubenRBS approved these changes

2024-01-03 10:32 UTC, RubenRBS requested changes
After speaking with the team, let's try to have both the %float formatter and the human readable timestamp in the output, see how that looks

2024-01-04 07:48 UTC, RubenRBS commented
This now looks something like this:
![image](https://github.com/conan-io/conan/assets/5364255/7fa7da94-e538-4236-8ae0-f90e5ba54407)

I've also added it to the normal --format=text output, I think this is ok

2024-01-04 08:37 UTC, memsharded commented
Looks good, I think we can move this forward with this (tests broken). How does the normal --format=text looks like on screen?

2024-01-04 11:26 UTC, RubenRBS commented
![Captura de pantalla 2024-01-04 a las 12 24 55](https://github.com/conan-io/conan/assets/5364255/2c1d1cd2-ea01-4c2c-9d07-2a3e4a1419b4)

2024-01-04 22:15 UTC, merged