Add warning to deprecate path functions in conanfile
conan-io/conan pull request #16247
Opened 2024-05-14 09:54 UTC by juansblanco

Changelog: Feature: Deprecate use of path functions in the conanfile
Docs: omit

There's a duplicity between the `path` and folder `functions` in the conanfile, for example `package_path` returns the value of `package_folder` but using the `Path` library. 
Also the `path` functions weren't documented, so they were not intended for use. 

For this reasons we are deprecating all the `path` functions and encourage use of the `folder` functions instead. Warnings were added to notify users when using the `path` functions to use the `folder` functions instead.

Closes: https://github.com/conan-io/conan/issues/12173
Related to: https://github.com/conan-io/docs/issues/2753

2024-05-14 10:01 UTC, memsharded requested changes

2024-05-14 10:01 UTC, memsharded commented on conans/model/conan_file.py
> +        new_function_name = function_name.replace("_path", "_folder")
No need to do this, you can pass the "source"; "build", explicitly as an argument

2024-05-14 10:01 UTC, memsharded commented on conans/model/conan_file.py
> +    def _deprecate_path_warning(self):
You need to start this with ``_conan_xxx``

2024-05-14 10:01 UTC, memsharded commented on conans/model/conan_file.py
> +        ConanOutput().warning(f"{self.display_name}: Use of '{function_name}' is deprecated, "
Use the ``self.output``

2024-05-14 10:28 UTC, memsharded approved these changes

2024-05-14 12:58 UTC, czoido approved these changes

2024-05-14 12:59 UTC, RubenRBS approved these changes

2024-05-14 13:05 UTC, merged

2024-06-25 10:34 UTC, shoeffner commented
edit: Now I found the explanations here: https://github.com/conan-io/conan/issues/12173#issuecomment-2099013311 , which clear some things up.


I am confused about this deprecation, as the related https://github.com/conan-io/docs/issues/2753 only mentions arguments for using pathlib instead of against it, followed by a decision against it. I know that for some of the ..._folder variables, no ..._path exists, but I would have preferred to add those and thus extend the support for `..._path`s in favor of going back to strings. I went through all places and replaced the use of `Path(..._folder)` with `..._path` when I found out about it a few months ago as we were using `Path(..._folder)` almost exclusively anyways, but also since it had the extra benefit of failing with a descriptive message if a ..._folder was not set with the `assert is not None` -- now we get a TypeError, so I guess that's still okay but slightly less descriptive. 

Luckily, resolving this deprecation is replacing all `..._path` calls with `Path(..._folder)` again and adding a couple of imports, so this is not a big issue for us :)

2024-06-27 16:34 UTC, memsharded commented
>  I know that for some of the ..._folder variables, no ..._path exists, but I would have preferred to add those and thus extend the support for ..._paths in favor of going back to strings. I went through all places and replaced the use of Path(..._folder) with ..._path when I found out about it a few months ago as we were using Path(..._folder) almost exclusively anyways, but also since it had the extra benefit of failing with a descriptive message if a ..._folder was not set with the assert is not None -- now we get a TypeError, so I guess that's still okay but slightly less descriptive.

Yes, probably the biggest factor was the fact that passing ``Path`` objects to some Conan inputs (like ``self.folders``, ``self.cpp_info``) would be breaking behavior, they expect to receive old ``os.path`` strings, and the API was more problematic, as something like ``self.folders.generators = self.build_path / "generators"`` would be breaking things, then users would request this to be supported, but this would create some risks (some of them are attributes, not methods), etc. 

> Luckily, resolving this deprecation is replacing all ..._path calls with Path(..._folder) again and adding a couple of imports, so this is not a big issue for us :)

Sorry about that. Even if it sounded a good idea initially, it was a mistake, and we should have followed the Python zen, to try to have only 1 way of doing things, and as the old ``os.path`` strings cannot be really removed, the ``Path()`` alternatives add more clutter than value, specially if the input interface cannot follow easily. We are at a moment after the Conan 1->2 transition that things better be more stable, and things that are mostly stylistic like this one, should have never progressed to code (even if it was not documented) in the first place. Thanks for your understanding!