Remove `ld` and `ar` from `tools.build:compiler_executables`
conan-io/conan pull request #16647
Opened 2024-07-10 13:55 UTC by ErniGH

Normally, people use the environment variables provided by each toolchain to introduce `ar` and `ld`. Additionally, no Conan toolchain implements either `ar` or `ld` from `tools.build:compiler_executables`. Therefore, I believe it is better to remove these variables to avoid future problems.

Close: #16517

2024-07-10 18:16 UTC, memsharded approved these changes

2024-07-10 20:26 UTC, AbrilRBS approved these changes

2024-07-11 05:24 UTC, czoido commented
Please, check the [gnutolchain](https://github.com/conan-io/conan/blob/671b46b36100b59964a991de8bdaf50a0502aa73/conan/tools/gnu/gnutoolchain.py#L134) I think we are using `ar` and `ld` there.

2024-07-11 05:24 UTC, czoido requested changes
Please, check the [gnutolchain](https://github.com/conan-io/conan/blob/671b46b36100b59964a991de8bdaf50a0502aa73/conan/tools/gnu/gnutoolchain.py#L134) I think we are using `ar` and `ld` there.

2024-07-11 07:27 UTC, franramirez688 commented
@ErniGH Yes, remove from the GnuToolchain that part too. I have no objection to keeping the same mapping there as it's done in the AutotoolsToolchain.

2024-07-11 09:28 UTC, czoido approved these changes

2024-07-11 10:01 UTC, merged