Fix 6483 do not download binary for conan info
conan-io/conan pull request #6487
Opened 2020-02-06 20:59 UTC by monsdar

Changelog: Fix: Do not download binary data during conan info when no remote is explicitly given by the user. Fixes #6483 
Docs: Not necessary??

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2020-02-06 20:59 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=6487) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=6487) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: monsdar<br/>:x: Nils Brinkmann<br/><hr/>**Nils Brinkmann** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=6487) it.</sub>

2020-02-06 21:03 UTC, monsdar commented
Seems the Git Log got messed up from within my fork... The older commits listed are all changes already merged into Conan or trivial (me updating my fork to the latest version of Conan). In one case I used a different Username (my real name), so it looks like two users have worked on this PR -.-

2020-02-07 08:38 UTC, memsharded requested changes

2020-02-07 08:38 UTC, memsharded commented on conans/client/graph/graph_binaries.py
> +        if remotes.selected:
This is breaking most of the binary-remote logic in Conan.

If no remote is explicitly selected, the location of the binary package is:
- The one defined from the binary package, if it was previously downloaded
- The one defined for the recipe, if the recipe is associated with a remote.

As you can see in the CI, a ton of tests are broken by this.

We need to understand better:
- If this is a regression, it seems it is not, the behavior has always been there
- I'd say that the binary is not really downloaded, but the server is actually queried for the information of it. That is what the ``conan info`` command does. The title might be a bit misleading.
- Disabling all remotes indeed should completely avoid contacting them, if true, that could be a bug, but not related to the ``remotes.selected`` specification of remote.

2020-02-07 09:51 UTC, jgsogo commented
@monsdar Thanks for trying to address the performance issue you detected in https://github.com/conan-io/conan/issues/6483 It looks like it requires a little bit more investigation, maybe, instead of using the `remotes.selected` it is about checking the `activated/deactivated` flag associated to them

2020-02-07 12:35 UTC, monsdar commented
Yeah, saw that it was breaking a lot of things as well. Would've been too easy if it was nothing more than this easy fix.

The question is if `conan info` really needs to gather info about remote binaries or not.
* If it does, perhaps there could be a parameter to control whether to query remotes or not
* If it doesn't perhaps it's possible to internally avoid querying the remotes for binary data

2020-02-07 12:36 UTC, monsdar commented
Let's rather continue the discussion within the Issue

2020-03-26 15:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=6487) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=6487) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: monsdar<br/>:x: Nils Brinkmann<br/><hr/>**Nils Brinkmann** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=6487) it.</sub>

2022-12-29 12:12 UTC, memsharded commented
PR https://github.com/conan-io/conan/pull/12807 should close this PR, it has been a long time, and it didn't move forward.
https://github.com/conan-io/conan/pull/12807 contains a rationale of the current behavior, which seems correct and expected, and not hitting the servers if the packages are in cache, and only hitting if they are not in cache.

2022-12-29 13:36 UTC, closed without merging

2022-12-29 13:38 UTC, memsharded commented
Closed by https://github.com/conan-io/conan/pull/12807, please check also related https://github.com/conan-io/conan/pull/12808 (for Conan 2.0)