fixing commands fail when no folder
conan-io/conan pull request #6825
Opened 2020-04-08 21:49 UTC by memsharded

Changelog: Fix: Avoid failures that happen when Conan runs in a non-existing folder
Docs: Omit

Close https://github.com/conan-io/conan/issues/6075

It also includes some minor pep8 fixes in the command.py file

2020-04-10 16:59 UTC, jgsogo approved these changes

2020-04-10 17:13 UTC, memsharded commented
I am moving this to draft. This responsibility is implemented already in the conan_api decorator, and in this point it wouldn't be necessary. The fix doesn't correct the error in the conan_api decorator.

2020-04-10 17:21 UTC, memsharded commented
Moved responsibility to api, removed from ``main()``. Please @jgsogo review again

2020-04-11 11:01 UTC, jgsogo requested changes
Not a review, just a comment:

There are many places in Conan where we are calling `os.getcwd` or `get_cwd` (btw, [why this file and comment](https://github.com/conan-io/conan/blob/develop/conans/unicode.py)?). This same _cryptic error_  can be raised at any of those places.

Before this PR, Conan was failing at the very beginning, now Conan can fail with this exception at many different places. I'm not sure if it is better to raise a meaningful error than to protect/bypass at this point.

wdyt?

2020-04-11 15:20 UTC, memsharded commented
> Not a review, just a comment:

> There are many places in Conan where we are calling os.getcwd or get_cwd (btw, why this file and comment?). This same cryptic error can be raised at any of those places.

> Before this PR, Conan was failing at the very beginning, now Conan can fail with this exception at many different places. I'm not sure if it is better to raise a meaningful error than to protect/bypass at this point.

>wdyt?

I have checked the code, in practice, many commands that do not require the current path (search, remove, upload), do not use ``getcwd`` at all, so I think this would be already an improvement for those commands.

For other commands, yes the error will be equally cryptic, and raised at different places. We could wrap in the ``get_cwd`` (was initially intended for unicode) for every ``os.getcwd()`` in the codebase (or at least in the first call of relevant commands), to protect against this error. Probably not worth, just a small UX improvement for a not critical thing.

2020-04-11 17:41 UTC, jgsogo approved these changes
Ok

2020-04-14 10:23 UTC, danimtb approved these changes

2020-04-14 10:24 UTC, merged