Do not fail with 'conan remove -r remote -p' if there are no packages in the remote
conan-io/conan pull request #7338
Opened 2020-07-10 15:28 UTC by jgsogo

Changelog: Bugfix: Do not fail for `conan remove -r remote -p` when there are no packages in the remote 
Docs: omit

Check there are no packages before trying to remove the package folder in the server. It prevents a 404 error.

close https://github.com/conan-io/conan/issues/7332

2020-07-13 09:04 UTC, czoido approved these changes

2020-07-13 15:21 UTC, uilianries approved these changes

2020-07-13 17:26 UTC, memsharded commented on conans/client/rest/rest_client_v1.py
> +        pcks = self.search_packages(ref, query=None)
I would only do the search if ``package_ids is None``, in other cases it should still raise.

Actually, I'd prefer capturing the raise, checking if package_ids is None, and re-raising if not, but I guess it is not easy to differentiate the 404 that the ``packages`` folder is missing or the 404 that the recipe is missing.

2020-07-13 17:26 UTC, memsharded commented on conans/client/rest/rest_client_v2.py
> +                package_search_url = self.router.search_packages(ref)
The ``search_packages`` is  quite slow, tbh, I am not very excited about this approach. I would say:

- This seems something to be fixed in the server side. I think it is a bug and can be fixed, it only belongs to the Conan API
- In the meantime, I would try to workaround it in the client side with a try - except 404 and only checking the ``search_packages()`` in that case. But annotating clearly it is a temporary workaround.

2020-07-13 19:01 UTC, jgsogo commented
Ok, I'll use this other approach, but I don't think it is something to fix in the server: the API is REST-based and we request a DELETE on a resource that doesn't exist, `404` is expected.

2020-07-13 22:53 UTC, memsharded commented
> Ok, I'll use this other approach, but I don't think it is something to fix in the server: the API is REST-based and we request a DELETE on a resource that doesn't exist, 404 is expected.

Yes you are right, it is true that in Api V2 it is a DELETE over ``ref/revision/packages`` path. It was not this way in Api V1.
So I agree. For me, the correct scenario would be that the 404 error is able to return the difference: it errors because the ``packages`` folder is not there, or it is failing because the package recipe is not there at all. There it would be possible for the client to act accordingly, raise RecipeNotFound or pass without raising. As this change requires too much work for little value, yes, please at least change the implementation to do the search() only for the failing 404 case.

2020-07-13 22:54 UTC, memsharded requested changes
Please change the impl so it only does ``search_packages`` for 404 responses, after the error, not before.

2020-07-14 16:27 UTC, memsharded approved these changes
Check the suggestion first, then merge, looking good.

2020-07-14 16:27 UTC, memsharded commented on conans/client/rest/rest_client_v1.py
> +        if ret.status_code == 404:
```suggestion
        if package_ids is None and ret.status_code == 404:
```

2020-07-15 08:18 UTC, memsharded commented on conans/client/rest/rest_client_v1.py
> +        if package_ids is not None and ret.status_code == 404:
I don't understand this change. The error in the server happens when we try to remove all the packages, and we don't specify ``package_ids``. If we explictly specify ``-p=<package_id>``, then, the 404 error is expected and desired.

2020-07-15 09:25 UTC, jgsogo commented
* `package_ids` is always a list (I'm removing the default value)
 * I'm  capturing any exception from the double-check operation, it would be misleading if it propagates and it would hide the original one.

2020-07-15 11:57 UTC, merged