Adds support of URL-like git ssh syntax
conan-io/conan pull request #7509
Opened 2020-08-05 18:13 UTC by wizardsd

Changelog:
This PR fixes adds support of URL-like addresses mentioned #5833 (as for me, it was a regression introduced in #4207)

According to https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols git supports two kinds of addresses, URL-like: ssh://[user@]server/project.git and scp-like: [user@]server:project.git

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

#PYVERS: Macos@py27, Windows@py36, Linux@py27, py34

2020-08-05 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=7509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=7509) before we can accept your contribution.<br/><hr/>**Roman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=7509) it.</sub>

2020-08-05 22:37 UTC, memsharded approved these changes

2020-08-10 16:38 UTC, jgsogo requested changes
Thanks for the PR! 🎉

2020-08-10 16:38 UTC, jgsogo commented on conans/test/unittests/client/tools/scm/test_scm_base.py
> +                             'ssh://git@github.com:2222/conan-io/conan.git'))
Add a test to check that we are actually removing the password:

```python
self.assertEqual('ssh://git@github.com:2222/conan-io/conan.git',
                         SCMBase._remove_credentials_url(
                             'ssh://git:passwd@github.com:2222/conan-io/conan.git'))
```

2020-08-10 17:20 UTC, jgsogo approved these changes
LGTM! Thanks!

2020-08-13 16:49 UTC, merged