fixing pkg_config empty dirs
conan-io/conan pull request #7703
Opened 2020-09-11 14:12 UTC by memsharded

Changelog: Bugfix: Fix ``pkg_config`` generator adding to .pc files empty include and lib dirs
Docs: Omit

Fix https://github.com/conan-io/conan/issues/7701

2020-09-14 07:30 UTC, SSE4 approved these changes
LGTM. maybe we also should filter framework paths, but I guess it's out of the scope.

2020-09-14 08:01 UTC, danimtb approved these changes

2020-09-14 15:10 UTC, jgsogo requested changes
Why all the `filter_empty = False`? That flag removes the paths that do not exist, but it doesn't turn an empty list `[]` into `None`, so the change should be useless in the context of this PR.

2020-09-14 19:53 UTC, memsharded commented
> Why all the filter_empty = False? That flag removes the paths that do not exist, but it doesn't turn an empty list [] into None, so the change should be useless in the context of this PR.

No, all those tests are broken otherwise. They are defining empty folder, that are being added to pkg_config despite being empty, and the default being ``filter_empty=True``. We need to either change the output (the .pc) checks, I thought it was more readable the change to define just the ``filter_empty=False``.

Anyway, the approach is not valid anyway, I need to fix it. Will review and update this PR, please tell me if you prefer the output of the tests changed instead of the filter_empty.

2020-09-14 19:53 UTC, memsharded commented on conans/client/generators/pkg_config.py
> +        if cpp_info.lib_paths:  # Make sure it is not empty
This is not valid. This can still add empty dirs to the .pc files.

2020-09-14 21:52 UTC, jgsogo commented
Better to change the output. Not sure if the `filter_empty` is something we want to keep as an attribute in the `cpp_info` object or closer to the place where the information is written/consumed (I think this second approach would be better).

2020-09-14 23:03 UTC, memsharded commented
I have changed some tests, others were very difficult or almost impossible to make it work without ``filter_empty=False``, for example when using absolute paths, as it is not possible to write in / for testing. So I have changed some of them, forcing the addition of files inside the folders, so they are not empy and the generated .pc files contain the information of folders.

2020-09-15 16:06 UTC, jgsogo approved these changes

2020-09-15 16:07 UTC, merged