[refact] What if... we use an inheritance based approach for CMake toolchains?
conan-io/conan pull request #7841
Opened 2020-10-07 14:32 UTC by jgsogo

Changelog: omit
Docs: omit

Main motivations here:

The generated toolchain file will be different for different cross-compiling scenarios. Probably some variables that make sense for some target architectures don't make sense for others (CMAKE_CXX_FLAGS). And for sure values will be different. 

I think that this _inheritance based_ approach will help us to keep source code cleaner:

The template itself:
 * the base template file can be simpler: probably a base template for variables and definitions that affect to every CMake based compilation: `set(...)`, `add_definitions(..)`, `BUILD_SHARED_LIBS`, `CMAKE_POSITION_INDEPENDENT_CODE`,... (or at least I'm pretty sure that, if they don't apply for a target platform, they will be ignored)
 * each inherited class can extend/append to that file the things that are specific to the target architecture. For example, the native one will add `-m64` to CONAN_CXX_FLAGS, while the Android one doesn't want to add anything there.

The logic inside the functions:
 * common logic can be implemented in the base file, but specific logic for a target platform can override the function and we will get rid of many nasty `if/else` to handle specific systems, cross-compiling logic, exceptional values,... 

At least this is the intention...

#tags: slow

2020-10-07 15:39 UTC, memsharded approved these changes
looks good to me

2020-10-07 17:23 UTC, jgsogo commented
I think that the test is failing because it is a cross-compiling scenario. I was not expecting to find it here. In purity it would require a `set(CMAKE_SYSTEM_NAME Linux)` but I need to have a closer look at it.

If building from `x86_64` to `x86` doesn't require cross-building machinery neither for Windows nor for Linux, then maybe it is our `cross_compiling()` function the one we should fix.

Open questions: is it a cross-compiling scenario? Do we want to set `CMAKE_SYSTEM_NAME` and get `CMAKE_CROSSCOMPILING` set? What is the difference between the two approaches?

2020-10-08 10:29 UTC, memsharded requested changes

2020-10-08 10:29 UTC, memsharded commented on conans/client/toolchain/cmake/__init__.py
> +    if not cross_building(conanfile, skip_x64_x86=skip_x64_x86):
I would simplify this, and add new logic only when the derived classes are really created. So at the moment I would have just 2, the Android one which is very clear, and another CMakeGenericToolchain() that could be now both cross-building and native, until someone actually does some cross compilation.

2020-10-08 11:23 UTC, memsharded approved these changes

2020-10-08 12:19 UTC, merged