Add Clang 11 in settings.yml
conan-io/conan pull request #7871
Opened 2020-10-13 14:18 UTC by uilianries

Changelog: Feature: Supports Clang 11
Docs: TODO

closes #7223

Clang 10 still uses C++14 by default and same flag for c++20 (c++2a). Thus, `_cppstd_clang` is totally fine.

https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html
https://releases.llvm.org/10.0.0/tools/clang/docs/index.html

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2020-10-13 14:41 UTC, memsharded requested changes

2020-10-13 14:41 UTC, memsharded commented on conans/client/migrations_settings.py
> +                  "8", "9", "10", "11"]
Not the right place to change it, you need to define a ``settings_1_30_2`` with a new value

2020-10-13 14:41 UTC, memsharded commented on conans/client/migrations_settings.py
> +                  "8", "9", "10", "11"]
Please include a check for this version in the cppstd tests

2020-10-13 16:01 UTC, uilianries commented on conans/client/migrations_settings.py
> +                  "8", "9", "10", "11"]
Done

2020-10-13 16:02 UTC, uilianries commented
It would be great if we could use Jinja for migrations_settings.py, that file has 1k8 lines!

2020-10-13 16:05 UTC, memsharded commented
> It would be great if we could use Jinja for migrations_settings.py, that file has 1k8 lines!

This will be removed in Conan 2.0

2020-10-13 16:07 UTC, memsharded commented on conans/test/unittests/client/build/cpp_std_flags_test.py
> +        for version in ["6", "7", "8", "9", "10"]:
And what about version "11"?

2020-10-14 12:40 UTC, uilianries commented on conans/test/unittests/client/build/cpp_std_flags_test.py
> +        for version in ["6", "7", "8", "9", "10"]:
Done, complete forgot the 11

2020-10-14 12:43 UTC, memsharded approved these changes

2020-10-14 13:38 UTC, merged