Fix: Allow modification of system/cpu_family/cpu/endian in generated MesonToolchain toolchain file
conan-io/conan pull request #8347
Opened 2021-01-18 07:47 UTC by SSE4

closes: #8312

based on #8266

Changelog: Fix: Allow modification of system/cpu_family/cpu/endian in generated MesonToolchain toolchain file
Docs: omit

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2021-02-09 15:42 UTC, memsharded commented on conans/test/functional/toolchains/meson/test_conf.py
> +    include(default)
Plese indent this so it is indented 1 more than ``profile_host`` variable.

2021-02-22 10:28 UTC, memsharded requested changes

2021-02-22 10:28 UTC, memsharded commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
I am concerned that this is an alternate way to have settings defined, totally bypassing the recipe and profile settings.
So you can have something in your profile settings, totally disconnected from the ``[conf]`` and it will still work.

I think the feature should be more oriented to complement definitions in ``settings`` than a full replacement. In that sense, what is desired is a mapping between custom user architectures and the toolchain values, but the input data should come from the settings, not directly from the [conf]. Please do a proof of concept of this approach.

2021-02-22 10:35 UTC, SSE4 commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
I am not sure I understand. there are no settings defined at all right now, if we are talking about conan settings (`settings.yml`). there are no settings like `os`, `compiler`, etc. defined in `conf`.

2021-02-22 10:49 UTC, memsharded commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
There should be some custom user settings to model different binaries. There are settings like architecture, that are being completely overriden by [conf]. You can put arch=x86 in your profile, and it will be ignored and build with armv8, because you said it in [conf]. This is incorrect.

The definitions for configurations should be settings as much as possible. Only very exceptional cases that wouldn't fit in settings could be possible. If a specific build system needs to map/convert those settings to its own representation, we can provide the mapping between settings and that representation in [conf] if necessary.

2021-02-22 11:11 UTC, SSE4 commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
if I understand correctly, the mapping should happen outside of conan then.
otherwise it's impossible to have custom settings supported that way.

2021-02-22 12:43 UTC, memsharded commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
Yes, it could serve the purpose of augmenting built-in mappings, like ``cpu_family_map``, to make it extensible for user custom settings. Where this mapping could live? There could be several options:
- Make it available in the toolchain, but it would require to modify recipes to account for it, not the best.
- Is it possible to pass mappings in ``[conf]``? Maybe it is possible to pass the values, or an external mapping file? (whatever we implement, lets discuss to make it a general approach for other build systems).

2021-02-22 12:49 UTC, SSE4 commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
let's be more specific :)
the feature request has started for Nintendo Switch (`arch=armv8`), so what should be in conf for that particular case?
I believe something like:
```
[conf]
tools.meson.mesontoolchain.armv8.build_machine = nintendo switch
```
or if we do a mapping in conf:
```
[conf]
tools.meson.mesontoolchain.build_machine_mapping = armv8: nintendo switch
```
do I understand your idea correctly?

2021-02-22 16:38 UTC, memsharded commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
I am not sure. I need to know the full input settings for ``os``, ``compiler``, etc, to know a bit better. If ``arch=armv8``, why not have it in the settings and just use it in Meson? I would say that ``Nintendo Switch`` should be a ``settings.os``, isn't it? If that requires to add an entry to ``system_map = {'Android': 'android',``, because it is not built-in and otherwise it will not map correctly, that is the behavior we are looking to inject into the ``MesonToolchain`` right? (and as many other build systems as possible whenever it makes sense)

2021-02-22 17:16 UTC, SSE4 commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
I am also not sure, it could be a weak defined area.
e.g. if PS4 runs FreeBSD (modified), should it be `os=FreeBSD` + `arch=x86_64`?
should it be different from regular (desktop) FreeBSD x86_64?
if I install vanilla FreeBSD on PS4, what should it be then?
and if PS5 also runs FreeBSD, should it also be the same settings combo?
or should we define `os.subsystem` for all these cases?
anyway, mapping could be very arbitrary (e.g. some devices don't even have OS at all, so it could be bare `arch` mapping for them).

2021-02-22 18:07 UTC, solvingj commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
Indeed, as @memsharded said, this is a clear example of an alternate way to define variables which will be sent to the compiler and will deeply impact the generated binary.  I agree that it undermines the basic automatic behavior that Conan settings are intended to provide, which is that changing any one of these compiler-related values will result in a changed `package_id`, and the build output will be treated as a separate binary.  

However, this seems so obvious, it leads me to the question: Why did @SSE4 not see it this way, and choose to try this implementation?

My guess is this:  
The default settings included with Conan don't contain any of the primitive abstractions (variables) which Meson uses for it's cross-building model.  Meanwhile, @SSE4 is tasked with trying to create a "generic" toolchain for Meson which is built-in with Conan works out of the box for most Meson users.  It seems completely impossible to deduce values for these Meson variables from Conan's existing settings. So, there are really only two choices:

1. Add these settings to Conan
2. Use `conf` in this way
3. Maintain a MesonToolchain which really isn't that useful out-of-the-box
 
@SSE4 please confirm or correct me if I am wrong. 

This does seem like a difficult choice to be honest.

2021-02-23 09:26 UTC, SSE4 commented on conan/tools/meson/toolchain.py
> +        build_machine_conf = self._conanfile.conf["tools.meson.mesontoolchain.build_machine"]
@solvingj yes, that's exactly it. I've been thinking about it, and I guess:
>  There are settings like architecture, that are being completely overriden by [conf].

this is not accurate. settings are not overridden, e.g. `package_id` will still have that is defined in settings. we only override particular build system specific variables, which might (or might not) match settings values.

a) so, may we have `settings.arch=x86` and have `arm` binaries built actually in package?
yes, we definitely can. it's already possible (e.g. via environment variables like `CFLAGS` or just by using another `gcc` executable)

b) should conan control/prevent that?
I don't think so, it's beyond of conan responsibilities

c) what do I need from conan?
I just want conan to allow me to specify arbitrary build system variables (e.g. `--host` in case of configure, env vars like `CFLAGS` or `machine` in case of meson). that things might be valid, or invalid, might or might not match the settings. it's basically garbage in - garbage out in this case, e.g. if I am specifying `settings.arch=x86` and then set `CFLAGS=-march=arm`, that's my problem, not conan's.

so there are two major approaches:
1. allow `conf` to directly specify low-level build system variables.

2. let user model his specific platform in `settings.yml` and then specify mapping for build system variables for:
2.1. cmake
2.2. autotools
2.3. meson
2.4. whatever else he might need

first off, approach 2. will not work if we declare mapping from settings to build system variables just in conan - it will require conan to model everything out of the box (all the exotic platforms), and if we missed something, it will require users either to wait for conan release, or to fork.

therefore, we need to define this new extensibility feature, and it seems like it should be turing complete (e.g. it cannot be modeled just by plain `conf` mechanism) - we don't know what could be all the custom settings and sub-settings, and how complicated could be that mapping in general way.

so in practice, approach 2. will require user to put python file implementing function like:
```
def get_build_system_variables(settings):
    vars = dict()
    if settings.os == "FreeBSD" and settings.os.subsystem = "Horizon" and self.settings.os.version = "2.0":
        vars["tools.meson.mesontoolchain.target_machine"] = "horizon"
    return vars
```
that seems to be only realistic and flexible enough approach.

still, I don't see huge benefit over 1. here: e.g. nothing prevents user from producing `arm` binaries for `settings.arch=x86` in that model, right?

but it seems like it was the problem we were trying to solve with approach 2., but it clearly failed, only introducing additional complexity.

2023-05-18 09:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=8347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=8347) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=8347) it.</sub>

2024-03-22 18:36 UTC, memsharded commented
Closing this as outdated and not planned.

Conan 2 already supports the ``tools.meson.mesontoolchain:extra_machine_files`` that allows passing Meson full machine files, in the same spirit that CMake toolchains can be passed to ``CMakeToolchain`` for any arbitrary configuration.

2024-03-22 18:36 UTC, closed without merging