fix generators_folder relative path to conanfile
conan-io/conan pull request #9668
Opened 2021-09-24 18:22 UTC by memsharded

Changelog: Bugfix: ``generator_folder`` was using the ``cwd`` instead of a relative folder to the conanfile, producing layout errors.
Docs: Omit

#tags: slow

2021-09-29 06:26 UTC, lasote requested changes
So, is this superseded by https://github.com/conan-io/conan/pull/9674/files ?
I would say this is breaking if not conditioned to the usage of the layout.

2021-09-30 11:00 UTC, franramirez688 commented on conans/test/functional/toolchains/ios/test_using_cmake.py
> +    @pytest.mark.tool_cmake(version="3.20")
We will need to add it in `conftest.py`, e.g.:

```python
        "3.20": {
            "path": {'Windows': 'C:/cmake/cmake-3.20.0-win64-x64/bin',
                     'Darwin': '/Users/jenkins/cmake/cmake-3.20.0/bin',
                     'Linux': '/usr/share/cmake-3.20.0/bin'}
        },
```

Anyway, let's wait for CI members to check out the final installation folders.

2021-10-04 13:38 UTC, lasote commented on conans/test/functional/toolchains/cmake/test_v2_cmake_template.py
> +    print(os.path.join(client.current_folder))
print

2021-10-04 13:41 UTC, lasote commented on conans/client/conan_api.py
> +            # FIXME: this is bad, but conanfile.folders.package=xxx is broken atm, cant be used
Please, explain.

2021-10-04 14:24 UTC, lasote commented on conans/client/conan_api.py
> +            # FIXME: this is bad, but conanfile.folders.package=xxx is broken atm, cant be used
I mean, I don't understand why/what is broken.

2021-10-04 15:33 UTC, lasote approved these changes
I think we should open an issue to fix `folders.package` or remove it if we really don't want it. But now, being hardcoded is useless.

2021-10-04 18:50 UTC, franramirez688 approved these changes

2021-10-05 06:48 UTC, merged

2021-10-22 12:27 UTC, yowidin commented on conan/tools/cmake/cmake.py
> +        arg_list = ["--install", build_folder, build_config, "--prefix", pkg_folder]
The `--install` command line argument isn't available in earlier versions of the CMake, it was probably introduced only in CMake 3.15. Please consider changing the call back to a build call with the `install` target.