Draft: Add multi-architecture generator for Xcode
conan-io/conan pull request #9669
Opened 2021-09-24 22:09 UTC by dheater

Changelog: Feature: Provide an `Xcode_multi` generator that handles multiple architectures.

Docs: https://github.com/conan-io/docs/pull/2234

Uses code provided by @kdonev example linked to #8403

My use case for this is supporting `x86_64` and `arm64 (M1)` conan packages without resorting to converting the conan library into a universal2 library

Relates to #1047
Closes #8403

NOTE: This seems like a good place to add `sdk=` attributes as well. I see people need this for `iphoneos` vs. `iphonesimulator` etc, but that is not the problem I am trying to solve at the moment

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [x] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one.

2021-09-24 22:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/conan?pullRequest=9669) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/conan?pullRequest=9669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/conan?pullRequest=9669) it.</sub>

2021-09-25 10:50 UTC, memsharded requested changes
Hi @dheater 

Thanks very much for your contribution.
However, we are already in the path to deprecate and remove this type of generator, and have already provided a bunch of new, experimental integrations, that you can see under the ``conan.tools.xxxx`` (note the singular ``conan.tools``) domain. The generators there:

- Are documented in https://docs.conan.io/en/latest/reference/conanfile/tools.html
- Do not extend ``Generator`` class
- They implement a ``generate()`` method, without arguments that saves to disk.
- They must use the new ``conanfile.dependencies`` interface to access dependencies information
- They must decouple dependencies information, like ``XCodeDeps``, from settings/toolchain configuration ``XCodeToolchain``, if necessary
- The dependencies information, if possible, should be able to generate 1 file per dependency, so projects with subprojects can add individual dependencies if necessary (don't know if this applies to XCode)
- They are ``multi-config`` by default, for multi-config systems

Please have a look at the implementation of MSBuildDeps (most likely the closest one to this one), and let us know if you think you could figure out how to approach it, or you would need help with that.

Many thanks!

2021-09-27 14:45 UTC, dheater commented
Closing. Work will be done in Conan 2.0

For anyone needing this capability in the meantime, See @kdonev's custom generator here: https://github.com/kdonev/conan-cmake-xcode-sample/blob/main/zmqWrapLib/xcode_multiarch/conanfile.py

You can generate a conan package for it (`xcode_multiarch/1.0`) and add it to your `[requires]`, then use by adding `XCodeMultiarchGenerator` to your `[generators]`

2021-09-28 08:40 UTC, memsharded commented
Hi @dheater 

Actually, it can totally be done in Conan 1.X, and probably should be done there to enable a smooth transition from 1.X to 2.0.

Are you closing this PR then, or prefer to keep it open for reference until the new one is done (by you, us, or anyone else)? Thanks.

2021-09-29 00:09 UTC, dheater commented
OK. Let's leave it open until another option is ready.

2021-10-19 18:01 UTC, gmeeker commented
Hi @dheater and @memsharded 
This is not exactly the same, but I've been researching the larger issue of making universal builds of CCI recipes, many of which don't use cmake or won't compile with the Xcode generator.  My idea was to support custom middleware that can wrap existing recipes, and all the knowledge of the lipo command can live outside of conan.  (The one I make can optionally detect the use of cmake and custom toolchains on a per-recipe basis.)  While this seems ambitious, it's also more general purpose (it can be used to add code signing, for example.)
I have a feature request to discuss the core changes, without universal support (handling multiple build dirs is a little more invasive), but I have previous branches with universal support as well.  Any comments are welcome.  I'm planning to continue working on this.

https://github.com/conan-io/conan/issues/9636

2021-10-19 18:12 UTC, memsharded commented
Just wanted to report: @czoido has started working on https://github.com/conan-io/conan/pull/9807 for implementing a new XcodeDeps generator with the latest new interfaces (prepared for Conan 2.0). Please track progress of that there, feedback welcome!

2021-10-22 11:07 UTC, memsharded commented
Hi @dheater 

@czoido has done lots of progress in https://github.com/conan-io/conan/pull/9807, which is close to be merged for next release in 1.42. I think that supersedes this PR. Thanks very much for contributing it, pushing this use case. Looking forward to your feedback of the new integration in 1.42.

2021-10-22 11:07 UTC, closed without merging

2021-10-25 16:14 UTC, memsharded commented
https://github.com/conan-io/conan/pull/9807 merged, ``XcodeDeps`` new generator will be available in Conan 1.42