Update the instructions created by the markdown generator
conan-io/conan pull request #9758
Opened 2021-10-07 12:08 UTC by tapia

Changelog: Feature: Update content created by the markdown generator.
Docs: https://github.com/conan-io/docs/pull/2380

Closes #9746 

(The following screenshot is incomplete, the list of headers is missing. Chrome didn't want me to export the full thing. You get the idea, though).

![dillinger io_factory_fetch_html](https://user-images.githubusercontent.com/589897/138124661-7f876dee-ebde-45a9-8eea-3321ca10947f.png)

2021-10-07 14:35 UTC, jgsogo reviewed
Can you render some examples of packages with more/less dependencies to see how they look like? I'll clone this branch and run examples, too.

OTH, we surely need @lasote here, I'm not familiarized enough with these generators so I'm not sure if this is the best way to use them.

2021-10-07 14:35 UTC, jgsogo commented on conans/client/generators/markdown.py
> +        [{{ dep_name }}/{{ dep_cpp_info.version }}]({{ dep_name }}){% if not loop.last %}, {% endif %}
This will break the links to the rest of the markdown files, right? I would say the `.md` is required, but I haven't tried it.

2021-10-07 15:51 UTC, tapia commented on conans/client/generators/markdown.py
> +        [{{ dep_name }}/{{ dep_cpp_info.version }}]({{ dep_name }}){% if not loop.last %}, {% endif %}
This is a "ConanCenter vs. local" problem. If we leave the `.md`, the Conan Center links will be broken (as they are right now in Staging. Check boost, for example).

2021-10-07 15:53 UTC, tapia commented
> OTH, we surely need @lasote here, I'm not familiarized enough with these generators so I'm not sure if this is the best way to use them.

I reviewed the template with him a few weeks ago, but I'm adding him as a reviewer so we can get his input

2021-10-07 16:38 UTC, jgsogo commented on conans/client/generators/markdown.py
> +        [{{ dep_name }}/{{ dep_cpp_info.version }}]({{ dep_name }}){% if not loop.last %}, {% endif %}
Sure, but probably the client should just work and on ConanCenter side we need to adapt the template or reinterpret these links on the HTML/JS side, right?

2021-10-08 07:44 UTC, tapia commented on conans/client/generators/markdown.py
> +        [{{ dep_name }}/{{ dep_cpp_info.version }}]({{ dep_name }}){% if not loop.last %}, {% endif %}
Done

2021-10-11 09:59 UTC, lasote requested changes

2021-10-11 09:59 UTC, lasote commented on conans/client/generators/markdown.py
> +    {% set cmake_find_package_filename = cpp_info.get_filename("cmake_find_package") %}
I would say these two lines (and the one calculating the component name) are not the most correct/complete. In the CMakeDeps generator we try to read first the properties (new ones) and if they doesn't exist we fallback to the old `get_name`. Check the CMakeDeps source code at `conan/tools/cmake/cmakedeps/templates/__init__.py`  methods `get_target_namespace` ,`get_global_target_name` , `get_component_alias` and `get_file_name`

2021-10-20 14:13 UTC, lasote requested changes

2021-10-20 14:13 UTC, lasote commented on conans/client/generators/markdown.py
> +    {% if requirement.new_cpp_info.components is iterable and requirement.new_cpp_info.components %}
Is this working using `new_cpp_info`? Is it rebased with develop?

2021-10-22 08:31 UTC, lasote requested changes
update the image after the changes, there are already missing changes (in the screenshot). It is much easier to review a rendered example.

2021-10-22 08:31 UTC, lasote commented on conans/client/generators/markdown.py
> +    Add these lines to your `CMakeLists.txt`:
```suggestion

    If you use it together with the `CMakeToolchain`, these `xxx-config.cmake` files will be found when you run a `find_package()` in your `CMakeLists.txt` file:
```

2021-10-22 08:31 UTC, lasote commented on conans/client/generators/markdown.py
> +    {% if requirement.cpp_info.components is iterable and requirement.cpp_info.components %}
remove extra \n here

2021-10-22 08:31 UTC, lasote commented on conans/client/generators/markdown.py
>      and another file for each of its components:
```suggestion
    and, if you want to use the components of the library separately, one `.pc` file per component:
```

2022-01-31 09:47 UTC, jgsogo commented
How does this look if rendered inside the ConanCenter webpage?

2022-01-31 10:44 UTC, lasote approved these changes
👍

2022-01-31 10:46 UTC, memsharded approved these changes

2022-01-31 10:57 UTC, jgsogo commented
btw, in the image I can see **two times** the information for `boost/1.77.0`. One should be enough 😄

2022-01-31 15:26 UTC, franramirez688 requested changes

2022-01-31 15:26 UTC, franramirez688 commented on conans/client/generators/markdown.py
> +    {% if requirement.cpp_info.components is iterable and requirement.cpp_info.components %}
Here too.

2022-01-31 15:26 UTC, franramirez688 commented on conans/client/generators/markdown.py
> +    {%- if requirement.cpp_info.components is iterable and requirement.cpp_info.components %}
Here too

2022-01-31 15:26 UTC, franramirez688 commented on conans/client/generators/markdown.py
> +    {% if requirement.cpp_info.components is iterable and requirement.cpp_info.components %}
I think this is a better approach to check empty lists:

```suggestion
    {% if requirement.cpp_info.components is defined and requirement.cpp_info.components|length > 0  %}
```

2022-01-31 15:33 UTC, franramirez688 commented on conans/client/generators/markdown.py
> +    {% if requirement.cpp_info.components is iterable and requirement.cpp_info.components %}
Even I think it should be enough to put:

 ```python
{% if requirement.cpp_info.components|length  %}
```

2022-01-31 16:55 UTC, franramirez688 approved these changes

2022-01-31 18:36 UTC, jgsogo approved these changes
Ok here.

2022-01-31 18:42 UTC, merged