Feature/refactor pkgconfigdeps
conan-io/conan pull request #9806
Opened 2021-10-15 10:36 UTC by franramirez688

Changelog: Feature: Refactor `conan.tools.gnu.pkgconfigdeps` module.
Docs: omit

Closes:  https://github.com/conan-io/conan/issues/9748

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2021-10-19 17:01 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +                requires = self._get_requires_names(dep, dep.cpp_info)
Just pass one ``dep`` argument, as the function can get inside the ``dep.cpp_info``

2021-10-19 17:01 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +class _SimplePCFile(object):
These classes with everything ``staticmethod`` sounds a bit OO abuse.

2021-10-19 17:01 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +                n = field if i == 0 else "%s%d" % (field, (i + 1))
This sounds a bit too much logic in the data preparation that could be moved to the rendering jinja part. How the file is rendered based on the input data is part of the template.

2021-10-20 07:48 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +                requires = self._get_requires_names(dep, dep.cpp_info)
Yes, but I'll have to pass it as `kwarg` because, at some point, I need to pass `dep` and `component.cpp_info`

2021-10-20 07:51 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +                requires = self._get_requires_names(dep, dep.cpp_info)
Ok, then you can leave it, I hadn't seen the case for components.

2021-10-20 09:43 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +                n = field if i == 0 else "%s%d" % (field, (i + 1))
There are other internal functions that are using those names like `get_cflags()` and `get_libs()` so it could be a mess to manage those names by the templates.

2021-10-20 11:05 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
>  def get_target_namespace(req):
PkgConfig doesn't have targets, does it? Maybe this should be renamed to `get_package_namespace`?

2021-10-20 11:05 UTC, tapia commented on conans/test/functional/toolchains/gnu/test_pkgconfigdeps.py
> +
Doesn't all this refactor need a single test?

2021-10-20 11:05 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +        def get_formmatted_dirs(field, folders, prefix_path_):
Typo: `formatted`, with a single m :-)

2021-10-20 11:05 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +        # Adding the dependency *.pc file (including its components as requires if any)
This comment needs to be rewritten, I don't understand what the part between parenthesis means. Maybe something like "which will include the 'requires' statement for the files generated in the previous loop"?

Also, the `complete_pc` and `simple_pc` names are quite confusing, it looks like they are two versions of the same file. Please give them a more descriptive name. If I understand correctly what they really are, how about `component_pc` and `main_package_pc` or something like that?

2021-10-20 11:05 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +                pc_files.update(self.get_components_pc_files(dep))
If `get_components_pc_files()` generates PC files, why don't you move it to the PCGenerator class, like `complete_pc_content()` and `simple_pc_content()`?

2021-10-20 11:23 UTC, franramirez688 commented on conans/test/functional/toolchains/gnu/test_pkgconfigdeps.py
> +
Actually, this refactor is completely covered by the current tests battery.

2021-10-20 11:26 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +                pc_files.update(self.get_components_pc_files(dep))
I see your point but I don't think so. Perhaps the problem is the naming and nothing else. Let me rethink these method names because I believe this comment is related to the previous one. Let's discuss it after updating the PR 😉

2021-10-20 12:19 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +                pc_files.update(self.get_components_pc_files(dep))
Sure 🙂

2021-10-21 06:47 UTC, lasote requested changes

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    def _get_requires_names(self, dep, cpp_info=None):
From `dep` you are using only the `dep.ref.name` and getting the `cppinfo` so it might be less confusing to have `_get_requires_names(self, name, cpp_info)` (cppinfo always required) ? 

And finally, `_get_requires_pc_names(self, name, cpp_info)` would be more consistent with my previous comment.

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +def get_package_namespace(req):
I wouldn't call it `namespace` either, it looks like it responds to some special property and the concept of namespace is not really a thing here in package config.
`get_package_name` should be enough.

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
>      if comp_name not in req.cpp_info.components:
`get_component_name` to be consistent with `get_package_name`

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    def _get_composed_pkg_config_name(pkg_name, comp_name):
`_get_pc_name` sounds friendly.

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_components_content(self, dep):
```suggestion
    def get_components_files_and_contents(self, dep):
```

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_short_pc_file_content(self, requires, name=None):
```suggestion
    def get_wrapper_pc_filename_and_content(self, requires, name=None):
```

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +                n = field if i == 0 else "%s%d" % (field, (i + 1))
> This sounds a bit too much logic in the data preparation that **could be moved to the rendering jinja part**.

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +        # for this one
Not sure about this logic or rule. 
So... we have a package `foo` declaring components `c1` and `c2`, and it will generate the following files:

```
foo-c1.pc
foo-c2.pc
foo.pc => Including `foo-c1.pc` and `foo-c2.pc`
```
Right?

But, if the author also declares a component `foo` we end with:

```
foo-c1.pc
foo-c2.pc
foo-foo.pc 
```

My question is, What is the problem of always generating a `foo.pc` file aggregating everything? I might be missing something...

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    long_content_template = textwrap.dedent("""\
```suggestion
    pc_file_template = textwrap.dedent("""\
```

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    short_content_template = textwrap.dedent("""\
```suggestion
    wrapper_pc_template = textwrap.dedent("""\
```

2021-10-21 06:47 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_long_pc_file_content(self, requires, name=None, cpp_info=None):
```suggestion
    def get_pc_filename_and_content(self, requires, name=None, cpp_info=None):
```

2021-10-21 07:37 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +        # Adding the dependency *.pc file (including its components as requires if any)
This is not really solved. You're still using names like `_get_composed_pkg_config_name()` or `get_long_pc_file_content()`, that don't give any clue about what they're actually doing.

2021-10-21 07:48 UTC, tapia reviewed
To summarize all my proposals:

`long_content_template` -> `component_pc_file_template`
`short_content_template` -> `package_pc_file_template`
`get_long_pc_file_content()` -> `get_component_pc_filename_and_content()`
`get_short_pc_file_content()` -> `get_package_pc_filename_and_content()`
`_get_composed_pkg_config_name()` -> `_get_pc_name()`

2021-10-21 07:48 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +    long_content_template = textwrap.dedent("""\
If I'm not wrong, this is only used for component's files. I'd call it `component_pc_file_template`.

2021-10-21 07:48 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +    short_content_template = textwrap.dedent("""\
Same thing here. This is only used for the general pc file. How about `package_pc_file_template`?

2021-10-21 07:48 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_long_pc_file_content(self, requires, name=None, cpp_info=None):
This would become `def get_component_pc_filename_and_content()`

2021-10-21 07:48 UTC, tapia commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_short_pc_file_content(self, requires, name=None):
And this would become `def get_package_pc_filename_and_content()`

2021-10-21 08:12 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +    long_content_template = textwrap.dedent("""\
This is used for components and non-components flow

2021-10-21 08:13 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +    short_content_template = textwrap.dedent("""\
The other template is being used for the main package and its components so the `package_pc_file_template` is confusing

2021-10-21 08:16 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +    def get_long_pc_file_content(self, requires, name=None, cpp_info=None):
It's not only related to components. Have a look at https://github.com/conan-io/conan/pull/9806/files#diff-4fc089c803914bd943aa1fb943fad3f054561571230e8c71540704af96af5a6eR105

2021-10-22 10:06 UTC, lasote commented on conan/tools/gnu/pkgconfigdeps.py
>          if pkg_name not in comp_names:
I think this still makes no sense. So if I declared a component "foo" and the package name is "foo" you don't generate a global `foo.pc`? What is the point? It would only make sense if the component is not scoped (foo_foo.pc => foo.pc) but it is always scoped, right?

2021-10-22 10:43 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
>          if pkg_name not in comp_names:
I even think this is a bug right now because, if we check legacy `PkgConfig` it was always creating a `foo.pc` regardless it was declared as a component or not. Now, we are creating either `foo-foo.pc` in case of being as a component or `foo.pc` in the opposite case. Then I agree with you that we should create always a `foo.pc`.

2021-10-22 11:55 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
>          if pkg_name not in comp_names:
Agree.

2021-10-25 16:22 UTC, memsharded approved these changes

2021-10-25 16:22 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +    {%- for _ in libdirs -%}
All the ``-`` in the template can be avoided using the jinja ``trim_blocks=True, lstrip_blocks=True,`` will take care of blanks, stripping them

2021-10-25 16:22 UTC, memsharded commented on conan/tools/gnu/pkgconfigdeps.py
> +        def get_formatted_dirs(folders, prefix_path_):
It is likely that in some situations we want pkg_config to run in a Windows subsystem, and then the ``subsystem_path()`` path formatting is necessary. It is ok as-is, but we might want to run subsystems testing for pkg_config too.

2021-10-25 17:35 UTC, franramirez688 commented on conan/tools/gnu/pkgconfigdeps.py
> +    {%- for _ in libdirs -%}
What I'm doing here it's to avoid this effect:

```
-L"${libdir1}"
-L"${libdir2}"
-L"${libdir3}"
```
I want all the values inline. Perhaps, I don't need all the signs but I put them just in case.

2021-10-26 15:05 UTC, czoido approved these changes

2021-10-27 16:17 UTC, merged