Component with same name as package
conan-io/conan pull request #9851
Opened 2021-10-22 13:19 UTC by franramirez688

Changelog: Feature: Let users define a new Component with the same name as the package.

Well, if you do that, Conan will raise this error:
```
ERROR:
	ConanException: pkg/0.1 package_info(): Component name cannot be the same as the package name: 'pkg'
```

This PR is aimed to solve this problem in relation to these comments:

* https://github.com/conan-io/conan/pull/9806#discussion_r733364484
* https://github.com/conan-io/conan/pull/9806#discussion_r734408718

Related PR: https://github.com/conan-io/conan/pull/9806
Docs: https://github.com/conan-io/docs/pull/XXXX

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the PEP8 style guides for Python code.
- [ ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 

<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags in the current PR body text.</sup>

2021-10-22 13:59 UTC, jgsogo commented
It would be helpful if you can summarize the scope of this PR. Besides the changes associated with `pkg_config`, how does it affect other generators? is this just to avoid the workaround? does it _fixes_ (breaking) the issue with `cmake_find_package` generator where the global target overrides (again) the overriding target?

2021-10-25 09:02 UTC, franramirez688 commented
> It would be helpful if you can summarize the scope of this PR. Besides the changes associated with `pkg_config`, how does it affect other generators? is this just to avoid the workaround? does it _fixes_ (breaking) the issue with `cmake_find_package` generator where the global target overrides (again) the overriding target?

Sure @jgsogo. I wanted to open a discussion about this logic. In summary, this PR is deleting the mechanism which is avoiding the creation of `components` with the same name as the package. I don't even know how it could affect other generators and that's the reason why I'm opening this PR. Actually, I realized about it due to I wanted to create a test for `foo-foo.pc` and I couldn't because of this piece of code, and, in my opinion, that's weird.
So, I guess, the reason is, as you said before:

> `cmake_find_package` generator where the global target overrides (again) the overriding target

Are we managing it because of it? or are there more reasons that I'm missing? Would it make sense each generator should deal with it in case of having any kind of collisions?

2021-10-25 10:00 UTC, danimtb commented
This restriction was introduced in order to avoid breaking recipes that were relying on the name of the main target. At that moment we did not have features such as `names` or `filenames`, not even `set_property()`. I'll explain why it was restricted with an example (I am talking about `cmake_find_package` here):
 
Let's say we got the recipe for `openssl` that does not declare components in `cpp_info` -> the generated CMake target will be ``openssl::openssl``. Any consumer could link to ``openssl::openssl`` when requiring the package (1).

In the case that `openssl` recipe started to use components, it could break consumers by not providing an ``openssl::openssl`` target, so to maintain compatibility, if a recipe declared any target, there would be always an ``openssl::openssl`` target generated that would include all the components to cover the use case described in (1).

I reckon this was done that way because the key of the `self.cpp_info.components` dict was the one used as name of the target. Probably now with the flexibility of properties, it could be possible to remove this restriction, making sure that the target ``openssl::openssl`` is always generated (?)

2021-10-25 12:00 UTC, lasote requested changes
A bit more context. This change would be needed for point 3) of https://github.com/conan-io/conan/issues/9848

I think this change is ok because:
 - If now Conan raises an exception and we remove the exception we are not breaking anything by definition. The only case would be someone relying on the Exception for something but that would be very weird and we will be able to manage it. So I think we cannot consider this "breaking" by any means.
 
 - We should unify the criteria, If a user changes a recipe introducing a new component with the name of the package, that should be interpreted by the generator as "Override the global target and use the component".  Maybe we should add a test to double-check that for the `CMakeDeps` and maybe the `cmake_find_package_multi` if possible.
 
 - If any generator couldn't manage a component named like the global (I don't know if that's the case) the generator can raise an error. But not the model. **So maybe we want to raise on every generator except the new ones moving that check removed to a function.** (to simplify the change and minimize the scope of this PR)

2021-10-25 16:26 UTC, jgsogo commented
I totally support the change. It would simplify some existing recipes, and avoid the current workaround we are doing to override the global target 🙌 


Nevertheless (and following Dani's comment), if we start to have a component with the same name of the package (recipes evolve to _accept_ this PR), it could break consumers that are already doing something like this to propagate information:

```python
def package_info(self):
    self.cpp_info.components["xxxx"].requires = ["openssl::openssl"]
```

This will no longer be all the `openssl` package, but only the things included in the _new_ non-forbidden component. It can break someone, but IMHO it's worth it (they should be using revisions, mirror recipes,...)

2021-10-26 07:20 UTC, lasote commented
Yeah, but you know, if we modify the recipe and remove the `.libs` list we are also breaking the consumers... that's ok.

2021-10-28 12:32 UTC, lasote commented
> I totally support the change. It would simplify some existing recipes, and avoid the current workaround we are doing to override the global target 🙌

About that, we need to decide the scope of this change, I think we should focus on the new generators only and for the old ones keep raising individually. I think that is the most conservative and the most aligned that what we are doing. IMHO we should focus on having recipes 2.0 compatible and forget about old integrations. @memsharded

2021-11-30 10:52 UTC, lasote commented
After the latest changes in the properties for CMakeDeps and PkgConfigDeps I would say I would move this to the 2.0 branch. About my previous comment:

> We should unify the criteria, If a user changes a recipe introducing a new component with the name of the package, that should be interpreted by the generator as "Override the global target and use the component". Maybe we should add a test to double-check that for the CMakeDeps and maybe the cmake_find_package_multi if possible.

I don't agree anymore, the component definition should be independent, a component could have the same name as the main package and then receive a rename with a property avoiding the collision, what we have to check is, in case of collisions, what would happen.

2021-11-30 11:28 UTC, franramirez688 commented
This PR does not make sense for Conan v2.x because this check does not exist. Closing the PR.

2021-11-30 11:28 UTC, closed without merging